title:              Blog
email:              sunmin9711@gmail.com
description:        A Blog
author:             Sun Min Lee
baseurl:            ""
url:                "https://sunminkr.github.io"

# Social Profiles
twitter_username:
github_username:    sunminkr
facebook_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:    # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

#tagging - http://tech.kakao.com/2016/07/07/tech-blog-story/
collections:
  tags:
    output: true
    premalink: /tags/:path/
    
default:
  - scope:
    path: ''
    type: tags
   values:
    layout: tag
