title: SUN MIN LEE
subtitle:
description: >- # this means to ignore newlines until "baseurl:"
  Computer Engineering student's personal portfolio homepage including CV and latest projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sunminkr.github.io" # the base hostname & protocol for your site, e.g. http://example.com

author_logo: profile.png
disqus_shortname: min-lee  #for comments using disqus
author: Sun Min Lee
author_bio: Hello, my name is Sun Min Lee. I am a senior undergraduate student in Computer Electronic System Engineering from Hankuk University of Foreign Studies. Feel free to take a look at my latest projects below.
author_email: "sunmin9711@gmail.com"
author_location: Seoul, South Korea
author_website_url: "http://sunminkr.github.io"

# social links
twitter_username: #yourusername
github_username:  sunminkr
facebook_username: #yourusername
linkedin_username: #yourusername
behance_username: #yourusername
instagram_username: #yourusername
medium_username: #yourusername
telegram_username: #yourusername
dribbble_username: #yourusername
flickr_username: #yourusername
